### ISSUE TITLE
invalid json

### ISSUE THREAD

**Issue by slowerthanlightspeed** [shoumma/organigram#1]
at:
http://organigram.surge.sh/#/

using json from:
https://json.org/example.html (and other sources)

response is:
"Sorry, the structure of the JSON file is not valid."

**Comment by shoumma** [comment]
Hi, the JSON structure requires to match the given example structure. Please take a look into the structure provided in the readme.md, or sample_json.json file. It was actually a requirement of the interview question that I should validate the structure of the json before attempting to render it as a tree.
